### ISSUE TITLE
Inject service definitions instead of using the `@=service()` notation

### ISSUE THREAD

**Issue by FabienPapet** [PrestaShop/ADR#30]
# Context

Today we have many different ways to make dependency injection into Prestashop. The purpose of this ADR is to unify all the ways for easier code understanding and maintenance.

```yaml
some_service_name:
  class: 'Some\Service\Class
  arguments:
    - "@=service('prestashop.adapter.legacy.context').getLanguages()"
```

There are many problems when we call DI. The main problem is that logic is is the YAML files, and we can't track function calls in the container, which hardens refactoring when we try to find usages. Also, we can call many times the same service to fetch different values. More, calls are made even if we don't use the result.

This also is a DX problem because autowiring can't be used and it goes against ADR 19.

# Proposition

The proposition is to stop using the `@=service` notation and injecting the used service instead. We however must be careful that we inject scoped services to avoid breaking the single responsibility principle. As well, legacy services should be avoided if possible and if there is a new service doing the same thing.

Injecting legacy services with legacy classes must also be avoided.

# Advantages

- DX Improved, easier understanding of the DI, and find function usages will be improved.
- We can make our services lazy if they need, that can also improve the performance if some services have too many dependencies.

# Inconvenient

- None as this is a continuous work and this does not require any work. 

# TLDR

Moving from this : 

```yaml

  form.type.sell.supplier:
    class: 'PrestaShopBundle\Form\Admin\Sell\Supplier\SupplierType'
    arguments:
      - '@prestashop.adapter.form.choice_provider.country_state_by_id'
      - '@=service("prestashop.adapter.legacy.context").getContext().country.id'
      - '@translator'
      - '@=service("prestashop.adapter.multistore_feature").isActive()'
      - '@router'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"
```

So it can be transformed into:

```yaml
  form.type.sell.supplier:
    class: 'PrestaShopBundle\Form\Admin\Sell\Supplier\SupplierType'
    arguments:
      - '@prestashop.adapter.form.choice_provider.country_state_by_id'
      - '@prestashop.adapter.legacy.context'
      - '@translator'
      - '@prestashop.adapter.multistore_feature'
      - '@router'
```

so the code will easier to understand and to maintain.
